---
title: "imansingh_Project3_VariablesAnalysis2"
author: "Iman Singh"
date: "11/2/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initialization}
#library(data.table)
library(ggplot2)
library(gridExtra)
library(tabplot)
#library(lsr)
library(corrplot)
library(dplyr)
library(VIM)
#library(caret)
#library(RANN)
library(reshape2)
house_train <- read.csv("~/Documents/NYC Data Science Academy/Project_3_Kaggle/train.csv", 
                        header = TRUE, 
                        na.strings = c("", "NA"),
                        stringsAsFactors = TRUE)
```

```{r model_subset}
house_sub <- house_train[,c(3,13,17,18,20,28,30,31,44,45,47,50,55,61,62,63,64,65,66,79,80,81)]

house_sub$SalePriceCat <- as.factor(as.numeric(cut_number(house_sub$SalePrice, 10)))

```

```{r variables}
variable_list = c('MSZoning','Neighborhood','HouseStyle','OverallQual','YearBuilt','ExterQual','Foundation','BsmtQual','X1stFlrSF','X2ndFlrSF','GrLivArea','FullBath','TotRmsAbvGrd','GarageFinish','GarageCars','GarageArea','GarageQual','GarageCond','PavedDrive','SaleType','SaleCondition')

numeric_variables = variable_list[c(4,5,9,10,11,12,13,15,16)]
ordinal_variables = variable_list[c(6,8,14,17,18,19)]
```


```{r hist_saleprice}
## histogram on SalePrice
grid.arrange(ggplot(house_train) + 
               geom_histogram(aes(SalePrice), bins = 20), 
             ggplot(house_train) + 
               geom_histogram(aes(log(SalePrice + 1)), bins = 20), 
             ncol = 2)
```

### table plot all features on sortded SalePrice
```{r density_plots}
colMtx <- matrix(names(house_sub)[1:length(house_sub)-1], nrow = 6)
for (i in 1:ncol(colMtx)) {
  tableplot(house_train, 
            select_string = c(colMtx[,i], "SalePrice"), 
            sortCol = "SalePrice", decreasing = TRUE, 
            nBins = 30)
}
```

### Correlations between Continuous Variables

```{r corrplot_numerical}
numeric_features <- names(house_sub)[sapply(house_sub, is.numeric)]
print(numeric_features)
corr_numtran <- cor(house_sub %>% 
                      select(one_of(numeric_features, "SalePrice")), 
                    method = "pearson", 
                    use = "pairwise.complete.obs")

corrplot(corr_numtran, method = "color", order="hclust")
cor(house_sub$FullBath, house_sub$SalePrice)
```

``` {r correlations_numerical}
attach(house_sub)
cor(OverallQual, SalePrice)
cor(YearBuilt, SalePrice)
cor(X1stFlrSF, SalePrice)
cor(X2ndFlrSF, SalePrice)
cor(GrLivArea, SalePrice)
cor(FullBath, SalePrice)
cor(TotRmsAbvGrd, SalePrice)
cor(GarageCars, SalePrice)
cor(GarageArea, SalePrice)
```

```{r histograms}
numeric_df <- house_sub %>% select(numeric_features)
numeric_melt  <- melt(numeric_df)
ggplot(data = numeric_melt, mapping = aes(x = value)) + 
    geom_histogram(bins = 10) + facet_wrap(~variable, scales = 'free_x')

```

```{r scatterplots}
library(theme)

g <- ggplot(house_sub, aes(y=SalePrice))

g + geom_point(aes(x=OverallQual))
g + geom_point(aes(x=YearBuilt))
g + geom_point(aes(x=X1stFlrSF))
g + geom_point(aes(x=X2ndFlrSF))
g + geom_point(aes(x=GrLivArea, color = OverallQual)) + scale_color_gradient(low = "brown", high = "yellow") + theme_dar
g + geom_point(aes(x=FullBath))
g + geom_point(aes(x=TotRmsAbvGrd))
g + geom_point(aes(x=GarageCars))
g + geom_point(aes(x=GarageArea))
```


# Correlations for Ordinal Values
```{r ordinal_features}
## ordinal features are those who contain one of the follow levels
corr_ordtran <- cor(data.matrix(house_sub %>% 
                                  select(one_of(ordinal_variables))),
                    method = "kendall", 
                    use = "pairwise.complete.obs")
corrplot(corr_ordtran, method = "color", order="hclust")
```

```{r barplots}
n_fun <- function(x){
  return(data.frame(y = median(x), label = paste0("n = ",length(x))))
}

g12 <- ggplot(data = house_sub, aes(x = GarageCars))
g12 + geom_histogram()

g0 <- ggplot(data = house_sub, aes(x = MSZoning))
g0 + geom_bar()
g0 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g1 <- ggplot(data = house_sub, aes(x = Neighborhood))
g1 + geom_bar() + coord_flip()
g1 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = .9), fun.data = n_fun, geom = "text") + coord_flip()

g2 <- ggplot(data = house_sub, aes(x = HouseStyle))
g2 + geom_bar()
g2 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g3 <- ggplot(data = house_sub, aes(x = ExterQual))
g3 + geom_bar()
g3 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g4 <- ggplot(data = house_sub, aes(x = Foundation))
g4 + geom_bar()
g4 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g5 <- ggplot(data = house_sub, aes(x = BsmtQual))
g5 + geom_bar()
g5 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g6 <- ggplot(data = house_sub, aes(x = GarageFinish))
g6 + geom_bar()
g6 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g7 <- ggplot(data = house_sub, aes(x = GarageQual))
g7 + geom_bar()
g7 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g8 <- ggplot(data = house_sub, aes(x = GarageCond))
g8 + geom_bar()
g8 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g9 <- ggplot(data = house_sub, aes(x = PavedDrive))
g9 + geom_bar()
g9 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g10 <- ggplot(data = house_sub, aes(x = SaleType))
g10 + geom_bar()
g10 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g11 <- ggplot(data = house_sub, aes(x = SaleCondition))
g11 + geom_bar()
g11 + geom_bar(aes(fill = SalePriceCat), position = 'fill') + scale_color_brewer("RdYlGn") + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

```



```{r boxplots}

#n_fun <- function(x){
#  return(data.frame(y = median(x), label = paste0("n = ",length(x))))
#}

g0 <- ggplot(data = house_sub, aes(x = MSZoning, y=SalePrice))
g0 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g1 <- ggplot(data = house_sub, aes(x = Neighborhood, y=SalePrice))
g1 + geom_boxplot() + stat_summary(aes(y = .9), fun.data = n_fun, geom = "text") + coord_flip()

g2 <- ggplot(data = house_sub, aes(x = HouseStyle, y=SalePrice))
g2 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g3 <- ggplot(data = house_sub, aes(x = ExterQual, y=SalePrice))
g3 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g4 <- ggplot(data = house_sub, aes(x = Foundation, y=SalePrice))
g4 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g5 <- ggplot(data = house_sub, aes(x = BsmtQual, y=SalePrice))
g5 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g6 <- ggplot(data = house_sub, aes(x = GarageFinish, y=SalePrice))
g6 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g7 <- ggplot(data = house_sub, aes(x = GarageQual, y=SalePrice))
g7 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g8 <- ggplot(data = house_sub, aes(x = GarageCond, y=SalePrice))
g8 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g9 <- ggplot(data = house_sub, aes(x = PavedDrive, y=SalePrice))
g9 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g10 <- ggplot(data = house_sub, aes(x = SaleType, y=SalePrice))
g10 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

g11 <- ggplot(data = house_sub, aes(x = SaleCondition, y=SalePrice))
g11 + geom_boxplot() + stat_summary(aes(y = 1.05), fun.data = n_fun, geom = "text")

```

#Missingness

#Categorical Values
``` {r na_sum1}
sum(is.na(MSZoning))
sum(is.na(Neighborhood))
sum(is.na(HouseStyle))
sum(is.na(OverallQual))
sum(is.na(YearBuilt))
sum(is.na(ExterQual))
sum(is.na(Foundation))
sum(is.na(BsmtQual))
sum(is.na(X1stFlrSF))
sum(is.na(X2ndFlrSF))
sum(is.na(GrLivArea))
sum(is.na(FullBath))
sum(is.na(TotRmsAbvGrd))
sum(is.na(GarageFinish))
sum(is.na(GarageCars))
sum(is.na(GarageArea))
sum(is.na(GarageQual))
sum(is.na(GarageCond))
sum(is.na(PavedDrive))
sum(is.na(SaleType))
sum(is.na(SaleCondition))
```


```{r missing_check}
## check missing values
col_missing <- names(house_sub)[colSums(is.na(house_sub)) > 0]
aggr(house_sub[,col_missing], prop = F, numbers = T)
Filter(function(x) x > 0, colSums(is.na(house_sub)))
```


``` {r numerical_outliers}
sum(OverallQual < (quantile(OverallQual, .25) - 1.5*IQR(OverallQual)))
sum(OverallQual > (quantile(OverallQual, .75) + 1.5*IQR(OverallQual)))
sum(YearBuilt < (quantile(YearBuilt, .25) - 1.5*IQR(YearBuilt)))
sum(YearBuilt > (quantile(YearBuilt, .75) + 1.5*IQR(YearBuilt)))
sum(X1stFlrSF < (quantile(X1stFlrSF, .25) - 1.5*IQR(X1stFlrSF)))
sum(X1stFlrSF > (quantile(X1stFlrSF, .75) + 1.5*IQR(X1stFlrSF)))
sum(X2ndFlrSF < (quantile(X2ndFlrSF, .25) - 1.5*IQR(X2ndFlrSF)))
sum(X2ndFlrSF > (quantile(X2ndFlrSF, .75) + 1.5*IQR(X2ndFlrSF)))
sum(GrLivArea < (quantile(GrLivArea, .25) - 1.5*IQR(GrLivArea)))
sum(GrLivArea > (quantile(GrLivArea, .75) + 1.5*IQR(GrLivArea)))
sum(FullBath < (quantile(FullBath, .25) - 1.5*IQR(FullBath)))
sum(FullBath > (quantile(FullBath, .75) + 1.5*IQR(FullBath)))
sum(TotRmsAbvGrd < (quantile(TotRmsAbvGrd, .25) - 1.5*IQR(TotRmsAbvGrd)))
sum(TotRmsAbvGrd > (quantile(TotRmsAbvGrd, .75) + 1.5*IQR(TotRmsAbvGrd)))
sum(GarageCars < (quantile(GarageCars, .25) - 1.5*IQR(GarageCars)))
sum(GarageCars > (quantile(GarageCars, .75) + 1.5*IQR(GarageCars)))
sum(GarageArea < (quantile(GarageArea, .25) - 1.5*IQR(GarageArea)))
sum(GarageArea > (quantile(GarageArea, .75) + 1.5*IQR(GarageArea)))
```

#Categorical Values
``` {r categorial_table}
apply(house_sub, MARGIN = 2, table)
```
```## R Markdown
